version: "3.8"

services:
  mysql_db:
    image: "mysql:8.0"
    container_name: muidb
    restart: always
    networks:
      - muinet
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_USER: yalo
      MYSQL_PASSWORD: yalo
      MYSQL_ROOT_PASSWORD: yalo
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  muinet:
    driver: bridge

volumes:
  mysql_data:
    driver: local
