version: "3.8"

services:
  muibackend:
    build: .
    ports:
      - "8088:8088"
    networks:
      - muinetwork
    depends_on:
      - mysqldb
  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_USER: yalo
      MYSQL_PASSWORD: yalo
      MYSQL_ROOT_PASSWORD: yalo
    networks:
      - muinetwork
networks:
  muinetwork: