version: "3.8"

services:
  mysql_db:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_USER: yalo
      MYSQL_PASSWORD: yalo
      MYSQL_ROOT_PASSWORD: yalo