server:
  port: 8088
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
  application:
    name: yalo
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/testdb
    username: yalo
    password: yalo
    driverClassName: com.mysql.jdbc.Driver
logging:
  level:
    sql: info
    root: info
    web: info
