server:
  port: 8088
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
  application:
    name: yalo
  datasource:
    url: jdbc:mysql://localhost:3306/testdb # local için
  #  url: jdbc:mysql://muidb:3306/testdb # docker için
    username: yalo
    password: yalo
    driverClassName: com.mysql.jdbc.Driver
logging:
  level:
    sql: info
    root: info
    web: info

